### ISSUE TITLE
Missing LICENSE file creates legal uncertainty for template usage

### ISSUE THREAD

**Issue by brylie** [ninetailsrabbit/indie-blueprint#4]
The project currently has a critical gap in its structure: there needs to be a LICENSE file in the GitHub repository. While the template is marked as MIT-licensed on the Godot Asset Library, this missing LICENSE file creates uncertainty and potential risks for developers hoping to use the template. Let me explain why this matters and how we can easily fix it.

## Understanding the Current Situation

When source code is published on GitHub without a license file, it automatically falls under default copyright law with "all rights reserved" status. This might seem counterintuitive since the code is publicly visible, but visibility doesn't equal permission to use. According to [GitHub's documentation on licensing](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), without an explicit license, all rights to the source code remain reserved, and no one may legally reproduce, distribute, or create derivative works from it.

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work
>
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

It's important to note that while an MIT license exists in the separate `indie-blueprint-docs` repository, that license does not extend to or cover this repository. Each repository needs an explicit license file to grant the necessary permissions for its code.

### Legal Barriers to Developers

Despite the code being publicly visible and marked as MIT-licensed on the Godot Asset Library, the absence of a LICENSE file on GitHub means developers technically cannot:
- Copy and modify the template code
- Distribute their modifications
- Create derivative works
- Include the template code in their projects

As Choose A License's guide (https://choosealicense.com/no-license/) explains, making code public or actively encouraging people to use it doesn't override this legal restriction. Only an explicit license grant can do that.

> If [developers] find software that doesn’t have a license, that generally means [they] have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow [them] to view and fork the code, this does not imply that [they] are permitted to use, modify, or share the software for any purpose.
>
> https://choosealicense.com/no-permission/

### Platform Inconsistency Creates Confusion

The current situation, where the template is marked as MIT-licensed on the Godot Asset Library but has no license on GitHub, creates several issues:
- Developers can't be sure which terms apply
- The project appears to have inconsistent policies
- Users might inadvertently violate copyright law while believing they're following the rules

## A Simple Solution

Adding a standard MIT LICENSE file to the GitHub repository would resolve these issues elegantly. The MIT license is particularly well-suited for template projects like this one because it:
- Grants developers clear permission to use, modify, and share the code
- Keeps attribution requirements minimal and straightforward
- Explicitly allows commercial use
- Protects template creators from liability
- Is widely recognized and understood in the developer community

## What This Change Won't Affect

It's important to note that adding the LICENSE file won't change:
- Developers' freedom to choose different licenses for their games
- The template's effectiveness as a starting point
- The current development workflow

## Benefits of Taking Action

By adding the LICENSE file, we:
1. Align the GitHub repository with the Godot Asset Library listing
2. Give developers clear legal permission to use the template
3. Remove barriers to adoption
4. Protect both the project and its users

**Comment by sempitern0** [comment]
Thanks for the clarification, after the reading it makes sense to put it in. I had no idea about the default non-license.

[Change here](https://github.com/ninetailsrabbit/indie-blueprint/commit/e4138ec0bc5bc96779b9e6e131976535b0fde54f)

**Comment by brylie** [comment]
Thanks for adding the license! :-)
