### ISSUE TITLE
Bro, when you are going to accept Discord friends invite?

### ISSUE THREAD

**Issue by kopeek** [ninetailsrabbit/indie-blueprint#5]
How I can help you in development of this project? maybe you want some things, but you don't have time? let me know :)

**Comment by sempitern0** [comment]
Sorry @kopeek I did not receive any invitation on discord and I don't see any pending.

 My time is limited and I'm adding things little by little, it's not really a project I have. If you want to contribute you can open pull requests and I'll check as soon as I can.

**Comment by kopeek** [comment]
I send invite to ninetailsrabbit

**Comment by sempitern0** [comment]
> I send invite to ninetailsrabbit

Ops sorry, my discord name actually is `n9rabbit`
